"""Reviewed v2.5 additions to the built-in Hebrew starter lexicon.

The records in this module are deliberately small, sense-specific, and
editorially controlled. Broad imported dictionary records belong to the
separate Kaikki/Wiktionary layer and must not inherit these visual cues.
"""

from __future__ import annotations

from typing import Any

STARTER_PROVENANCE_V2 = "Ivrit Sheli editorial review; A0/A1 Israel-life sense v2"


def _concept(
    *,
    word: str,
    niqqud: str,
    romanization: str,
    pos: str,
    gloss_en: str,
    gloss_es: str,
    category: str,
    level: str,
    visual_key: str,
    visual_emoji: str,
    visual_alt_en: str,
    visual_alt_es: str,
    visual_alt_he: str,
    example_he: str,
    example_en: str,
    example_es: str,
    example_romanization: str,
    gender: str | None = None,
) -> dict[str, Any]:
    """Return one exact reviewed sense in the dictionary seed format."""
    return {
        "word": word,
        "pos": pos,
        "romanization": romanization,
        "gender": gender,
        # Root and binyan stay unknown unless a reviewed source establishes them.
        "root": None,
        "binyan": None,
        "source_key": None,
        "gloss_en": gloss_en,
        "gloss_es": gloss_es,
        "level": level,
        "category": category,
        "visual_key": visual_key,
        "visual_emoji": visual_emoji,
        "visual_alt_en": visual_alt_en,
        "visual_alt_es": visual_alt_es,
        "visual_alt_he": visual_alt_he,
        "provenance": STARTER_PROVENANCE_V2,
        "forms": [{"form": niqqud, "tags": ["with-niqqud"]}],
        "examples": [
            {
                "hebrew": example_he,
                "translation_en": example_en,
                "translation_es": example_es,
                "romanization": example_romanization,
            }
        ],
    }


EXPANDED_STARTER_ENTRIES: tuple[dict[str, Any], ...] = (
    # Greetings: four additions bring the category to twelve concepts.
    _concept(
        word="ערב טוב",
        niqqud="עֶרֶב טוֹב",
        romanization="erev tov",
        pos="phrase",
        gloss_en="good evening",
        gloss_es="buenas tardes",
        category="greetings",
        level="A0",
        visual_key="greetings.good_evening",
        visual_emoji="🌇",
        visual_alt_en="A warm Israeli evening skyline",
        visual_alt_es="Un horizonte israelí cálido al atardecer",
        visual_alt_he="קו רקיע ישראלי בשעת ערב",
        example_he="עֶרֶב טוֹב לְכֻלָּם.",
        example_en="Good evening, everyone.",
        example_es="Buenas tardes a todos.",
        example_romanization="Erev tov le-kulam.",
    ),
    _concept(
        word="לילה טוב",
        niqqud="לַיְלָה טוֹב",
        romanization="laila tov",
        pos="phrase",
        gloss_en="good night",
        gloss_es="buenas noches",
        category="greetings",
        level="A0",
        visual_key="greetings.good_night",
        visual_emoji="🌙",
        visual_alt_en="A quiet moon above sleeping homes",
        visual_alt_es="Una luna tranquila sobre casas dormidas",
        visual_alt_he="ירח שקט מעל בתים ישנים",
        example_he="לַיְלָה טוֹב, נִתְרָאֶה מָחָר.",
        example_en="Good night, see you tomorrow.",
        example_es="Buenas noches, nos vemos mañana.",
        example_romanization="Laila tov, nitra'e makhar.",
    ),
    _concept(
        word="מה נשמע",
        niqqud="מַה נִּשְׁמָע?",
        romanization="ma nishma",
        pos="phrase",
        gloss_en="how are things?",
        gloss_es="¿qué tal?",
        category="greetings",
        level="A0",
        visual_key="greetings.how_are_things",
        visual_emoji="🙂",
        visual_alt_en="Two neighbors greeting each other",
        visual_alt_es="Dos vecinos saludándose",
        visual_alt_he="שני שכנים מברכים זה את זה",
        example_he="מַה נִּשְׁמָע הַיּוֹם?",
        example_en="How are things today?",
        example_es="¿Qué tal hoy?",
        example_romanization="Ma nishma ha-yom?",
    ),
    _concept(
        word="נעים מאוד",
        niqqud="נָעִים מְאֹד",
        romanization="na'im me'od",
        pos="phrase",
        gloss_en="nice to meet you",
        gloss_es="mucho gusto",
        category="greetings",
        level="A0",
        visual_key="greetings.nice_to_meet_you",
        visual_emoji="🤝",
        visual_alt_en="Two people meeting with a friendly handshake",
        visual_alt_es="Dos personas conociéndose con un apretón de manos",
        visual_alt_he="שני אנשים נפגשים בלחיצת יד ידידותית",
        example_he="שָׁלוֹם, נָעִים מְאֹד.",
        example_en="Hello, nice to meet you.",
        example_es="Hola, mucho gusto.",
        example_romanization="Shalom, na'im me'od.",
    ),
    # Family: five additions bring the category to twelve concepts.
    _concept(
        word="הורים",
        niqqud="הוֹרִים",
        romanization="horim",
        pos="noun",
        gloss_en="parents",
        gloss_es="padres",
        category="family",
        level="A0",
        visual_key="family.parents",
        visual_emoji="🧑‍🧑‍🧒",
        visual_alt_en="Parents standing together with their child",
        visual_alt_es="Padres junto a su hijo",
        visual_alt_he="הורים עומדים יחד עם ילדם",
        example_he="הַהוֹרִים שֶׁלִּי בַּבַּיִת.",
        example_en="My parents are at home.",
        example_es="Mis padres están en casa.",
        example_romanization="Ha-horim sheli ba-bayit.",
        gender="masculine plural",
    ),
    _concept(
        word="בן",
        niqqud="בֵּן",
        romanization="ben",
        pos="noun",
        gloss_en="son",
        gloss_es="hijo",
        category="family",
        level="A0",
        visual_key="family.son",
        visual_emoji="👦",
        visual_alt_en="A son standing beside his parent",
        visual_alt_es="Un hijo junto a uno de sus padres",
        visual_alt_he="בן עומד ליד אחד מהוריו",
        example_he="יֵשׁ לָהּ בֵּן אֶחָד.",
        example_en="She has one son.",
        example_es="Ella tiene un hijo.",
        example_romanization="Yesh lah ben ekhad.",
        gender="masculine",
    ),
    _concept(
        word="בת",
        niqqud="בַּת",
        romanization="bat",
        pos="noun",
        gloss_en="daughter",
        gloss_es="hija",
        category="family",
        level="A0",
        visual_key="family.daughter",
        visual_emoji="👧",
        visual_alt_en="A daughter standing beside her parent",
        visual_alt_es="Una hija junto a uno de sus padres",
        visual_alt_he="בת עומדת ליד אחד מהוריה",
        example_he="יֵשׁ לָהּ בַּת אַחַת.",
        example_en="She has one daughter.",
        example_es="Ella tiene una hija.",
        example_romanization="Yesh lah bat akhat.",
        gender="feminine",
    ),
    _concept(
        word="ילד",
        niqqud="יֶלֶד",
        romanization="yeled",
        pos="noun",
        gloss_en="boy",
        gloss_es="niño",
        category="family",
        level="A0",
        visual_key="family.boy",
        visual_emoji="🧒",
        visual_alt_en="A boy reading a book",
        visual_alt_es="Un niño leyendo un libro",
        visual_alt_he="ילד קורא ספר",
        example_he="הַיֶּלֶד קוֹרֵא סֵפֶר.",
        example_en="The boy is reading a book.",
        example_es="El niño está leyendo un libro.",
        example_romanization="Ha-yeled kore sefer.",
        gender="masculine",
    ),
    _concept(
        word="ילדה",
        niqqud="יַלְדָּה",
        romanization="yalda",
        pos="noun",
        gloss_en="girl",
        gloss_es="niña",
        category="family",
        level="A0",
        visual_key="family.girl",
        visual_emoji="🧒",
        visual_alt_en="A girl drinking a glass of water",
        visual_alt_es="Una niña bebiendo un vaso de agua",
        visual_alt_he="ילדה שותה כוס מים",
        example_he="הַיַּלְדָּה שׁוֹתָה מַיִם.",
        example_en="The girl is drinking water.",
        example_es="La niña está bebiendo agua.",
        example_romanization="Ha-yalda shota mayim.",
        gender="feminine",
    ),
    # Home: five additions bring the category to twelve concepts.
    _concept(
        word="דלת",
        niqqud="דֶּלֶת",
        romanization="delet",
        pos="noun",
        gloss_en="door",
        gloss_es="puerta",
        category="home",
        level="A0",
        visual_key="home.door",
        visual_emoji="🚪",
        visual_alt_en="An open front door",
        visual_alt_es="Una puerta de entrada abierta",
        visual_alt_he="דלת כניסה פתוחה",
        example_he="הַדֶּלֶת פְּתוּחָה.",
        example_en="The door is open.",
        example_es="La puerta está abierta.",
        example_romanization="Ha-delet ptukha.",
        gender="feminine",
    ),
    _concept(
        word="חלון",
        niqqud="חַלּוֹן",
        romanization="khalon",
        pos="noun",
        gloss_en="window",
        gloss_es="ventana",
        category="home",
        level="A0",
        visual_key="home.window",
        visual_emoji="🪟",
        visual_alt_en="Sunlight coming through a window",
        visual_alt_es="Luz del sol entrando por una ventana",
        visual_alt_he="אור שמש נכנס דרך חלון",
        example_he="הַחַלּוֹן גָּדוֹל.",
        example_en="The window is big.",
        example_es="La ventana es grande.",
        example_romanization="Ha-khalon gadol.",
        gender="masculine",
    ),
    _concept(
        word="מקלחת",
        niqqud="מִקְלַחַת",
        romanization="miklakhat",
        pos="noun",
        gloss_en="shower",
        gloss_es="ducha",
        category="home",
        level="A1",
        visual_key="home.shower",
        visual_emoji="🚿",
        visual_alt_en="A clean shower with running water",
        visual_alt_es="Una ducha limpia con agua corriente",
        visual_alt_he="מקלחת נקייה עם מים זורמים",
        example_he="הַמִּקְלַחַת בַּחֶדֶר הַזֶּה.",
        example_en="The shower is in this room.",
        example_es="La ducha está en esta habitación.",
        example_romanization="Ha-miklakhat ba-kheder ha-ze.",
        gender="feminine",
    ),
    _concept(
        word="שירותים",
        niqqud="שֵׁרוּתִים",
        romanization="sherutim",
        pos="noun",
        gloss_en="bathroom",
        gloss_es="baño",
        category="home",
        level="A0",
        visual_key="home.bathroom",
        visual_emoji="🚻",
        visual_alt_en="A clear public bathroom sign",
        visual_alt_es="Una señal clara de baño público",
        visual_alt_he="שלט ברור לשירותים ציבוריים",
        example_he="אֵיפֹה הַשֵּׁרוּתִים?",
        example_en="Where is the bathroom?",
        example_es="¿Dónde está el baño?",
        example_romanization="Eifo ha-sherutim?",
        gender="masculine plural",
    ),
    _concept(
        word="מקרר",
        niqqud="מְקָרֵר",
        romanization="mekarer",
        pos="noun",
        gloss_en="refrigerator",
        gloss_es="refrigerador",
        category="home",
        level="A1",
        visual_key="home.refrigerator",
        visual_emoji="🧊",
        visual_alt_en="A refrigerator with food inside",
        visual_alt_es="Un refrigerador con comida dentro",
        visual_alt_he="מקרר עם אוכל בתוכו",
        example_he="הֶחָלָב בַּמְּקָרֵר.",
        example_en="The milk is in the refrigerator.",
        example_es="La leche está en el refrigerador.",
        example_romanization="He-khalav ba-mekarer.",
        gender="masculine",
    ),
    # Food: four additions bring the category to twelve concepts.
    _concept(
        word="גבינה",
        niqqud="גְּבִינָה",
        romanization="gvina",
        pos="noun",
        gloss_en="cheese",
        gloss_es="queso",
        category="food",
        level="A0",
        visual_key="food.cheese",
        visual_emoji="🧀",
        visual_alt_en="A piece of cheese on a plate",
        visual_alt_es="Un trozo de queso en un plato",
        visual_alt_he="חתיכת גבינה על צלחת",
        example_he="יֵשׁ גְּבִינָה בַּמְּקָרֵר.",
        example_en="There is cheese in the refrigerator.",
        example_es="Hay queso en el refrigerador.",
        example_romanization="Yesh gvina ba-mekarer.",
        gender="feminine",
    ),
    _concept(
        word="ביצה",
        niqqud="בֵּיצָה",
        romanization="beitsa",
        pos="noun",
        gloss_en="egg",
        gloss_es="huevo",
        category="food",
        level="A0",
        visual_key="food.egg",
        visual_emoji="🥚",
        visual_alt_en="A cooked egg on a plate",
        visual_alt_es="Un huevo cocido en un plato",
        visual_alt_he="ביצה מבושלת על צלחת",
        example_he="הַבֵּיצָה חַמָּה.",
        example_en="The egg is hot.",
        example_es="El huevo está caliente.",
        example_romanization="Ha-beitsa khama.",
        gender="feminine",
    ),
    _concept(
        word="מסעדה",
        niqqud="מִסְעָדָה",
        romanization="mis'ada",
        pos="noun",
        gloss_en="restaurant",
        gloss_es="restaurante",
        category="food",
        level="A0",
        visual_key="food.restaurant",
        visual_emoji="🍽️",
        visual_alt_en="A welcoming neighborhood restaurant",
        visual_alt_es="Un restaurante acogedor del barrio",
        visual_alt_he="מסעדה שכונתית מזמינה",
        example_he="הַמִּסְעָדָה פְּתוּחָה.",
        example_en="The restaurant is open.",
        example_es="El restaurante está abierto.",
        example_romanization="Ha-mis'ada ptukha.",
        gender="feminine",
    ),
    _concept(
        word="טעים",
        niqqud="טָעִים",
        romanization="ta'im",
        pos="adjective",
        gloss_en="tasty",
        gloss_es="sabroso",
        category="food",
        level="A0",
        visual_key="food.tasty",
        visual_emoji="😋",
        visual_alt_en="A happy diner enjoying a tasty salad",
        visual_alt_es="Una persona disfrutando de una ensalada sabrosa",
        visual_alt_he="סועד נהנה מסלט טעים",
        example_he="הַסָּלָט טָעִים.",
        example_en="The salad is tasty.",
        example_es="La ensalada está sabrosa.",
        example_romanization="Ha-salat ta'im.",
        gender="masculine",
    ),
    # Transport: six additions bring the category to twelve concepts.
    _concept(
        word="אופניים",
        niqqud="אוֹפַנַּיִם",
        romanization="ofanayim",
        pos="noun",
        gloss_en="bicycle",
        gloss_es="bicicleta",
        category="transport",
        level="A1",
        visual_key="transport.bicycle",
        visual_emoji="🚲",
        visual_alt_en="A bicycle beside a city bike lane",
        visual_alt_es="Una bicicleta junto a un carril urbano",
        visual_alt_he="אופניים ליד שביל אופניים עירוני",
        example_he="יֵשׁ לִי אוֹפַנַּיִם.",
        example_en="I have a bicycle.",
        example_es="Tengo una bicicleta.",
        example_romanization="Yesh li ofanayim.",
        gender="masculine plural",
    ),
    _concept(
        word="רכב",
        niqqud="רֶכֶב",
        romanization="rekhev",
        pos="noun",
        gloss_en="vehicle",
        gloss_es="vehículo",
        category="transport",
        level="A1",
        visual_key="transport.vehicle",
        visual_emoji="🚗",
        visual_alt_en="A small vehicle parked beside a home",
        visual_alt_es="Un vehículo pequeño estacionado junto a una casa",
        visual_alt_he="רכב קטן חונה ליד בית",
        example_he="הָרֶכֶב לְיַד הַבַּיִת.",
        example_en="The vehicle is beside the house.",
        example_es="El vehículo está junto a la casa.",
        example_romanization="Ha-rekhev le-yad ha-bayit.",
        gender="masculine",
    ),
    _concept(
        word="נהג",
        niqqud="נַהָג",
        romanization="nahag",
        pos="noun",
        gloss_en="driver",
        gloss_es="conductor",
        category="transport",
        level="A1",
        visual_key="transport.driver",
        visual_emoji="🚌",
        visual_alt_en="A bus driver waiting at a station",
        visual_alt_es="Un conductor de autobús esperando en una estación",
        visual_alt_he="נהג אוטובוס מחכה בתחנה",
        example_he="הַנַּהָג מְחַכֶּה בַּתַּחֲנָה.",
        example_en="The driver is waiting at the station.",
        example_es="El conductor espera en la estación.",
        example_romanization="Ha-nahag mekhake ba-takhana.",
        gender="masculine",
    ),
    _concept(
        word="מפה",
        niqqud="מַפָּה",
        romanization="mapa",
        pos="noun",
        gloss_en="map",
        gloss_es="mapa",
        category="transport",
        level="A1",
        visual_key="transport.map",
        visual_emoji="🗺️",
        visual_alt_en="A folded map marked with a route",
        visual_alt_es="Un mapa doblado con una ruta marcada",
        visual_alt_he="מפה מקופלת עם מסלול מסומן",
        example_he="הַמַּפָּה בַּתִּיק.",
        example_en="The map is in the bag.",
        example_es="El mapa está en la bolsa.",
        example_romanization="Ha-mapa ba-tik.",
        gender="feminine",
    ),
    _concept(
        word="ימינה",
        niqqud="יָמִינָה",
        romanization="yamina",
        pos="adverb",
        gloss_en="to the right",
        gloss_es="a la derecha",
        category="transport",
        level="A1",
        visual_key="transport.right",
        visual_emoji="➡️",
        visual_alt_en="A route arrow turning right",
        visual_alt_es="Una flecha de ruta girando a la derecha",
        visual_alt_he="חץ מסלול פונה ימינה",
        example_he="פְּנֵה יָמִינָה בָּרְחוֹב הַבָּא.",
        example_en="Turn right at the next street.",
        example_es="Gira a la derecha en la próxima calle.",
        example_romanization="Pne yamina ba-rekhov ha-ba.",
    ),
    _concept(
        word="שמאלה",
        niqqud="שְׂמֹאלָה",
        romanization="smola",
        pos="adverb",
        gloss_en="to the left",
        gloss_es="a la izquierda",
        category="transport",
        level="A1",
        visual_key="transport.left",
        visual_emoji="⬅️",
        visual_alt_en="A route arrow turning left",
        visual_alt_es="Una flecha de ruta girando a la izquierda",
        visual_alt_he="חץ מסלול פונה שמאלה",
        example_he="פְּנֵה שְׂמֹאלָה בָּרְחוֹב הַבָּא.",
        example_en="Turn left at the next street.",
        example_es="Gira a la izquierda en la próxima calle.",
        example_romanization="Pne smola ba-rekhov ha-ba.",
    ),
    # Shopping: six additions bring the category to twelve concepts.
    _concept(
        word="שקל",
        niqqud="שֶׁקֶל",
        romanization="shekel",
        pos="noun",
        gloss_en="shekel",
        gloss_es="séquel",
        category="shopping",
        level="A0",
        visual_key="shopping.shekel",
        visual_emoji="🪙",
        visual_alt_en="Israeli shekel coins",
        visual_alt_es="Monedas de séquel israelí",
        visual_alt_he="מטבעות שקל ישראלי",
        example_he="זֶה עוֹלֶה עֲשָׂרָה שְׁקָלִים.",
        example_en="This costs ten shekels.",
        example_es="Esto cuesta diez séqueles.",
        example_romanization="Ze ole asara shkalim.",
        gender="masculine",
    ),
    _concept(
        word="קבלה",
        niqqud="קַבָּלָה",
        romanization="kabala",
        pos="noun",
        gloss_en="receipt",
        gloss_es="recibo",
        category="shopping",
        level="A1",
        visual_key="shopping.receipt",
        visual_emoji="🧾",
        visual_alt_en="A printed shop receipt",
        visual_alt_es="Un recibo impreso de una tienda",
        visual_alt_he="קבלה מודפסת מחנות",
        example_he="אֶפְשָׁר קַבָּלָה, בְּבַקָּשָׁה?",
        example_en="Can I have a receipt, please?",
        example_es="¿Me da un recibo, por favor?",
        example_romanization="Efshar kabala, bevakasha?",
        gender="feminine",
    ),
    _concept(
        word="מזומן",
        niqqud="מְזֻמָּן",
        romanization="mezuman",
        pos="noun",
        gloss_en="cash",
        gloss_es="efectivo",
        category="shopping",
        level="A1",
        visual_key="shopping.cash",
        visual_emoji="💵",
        visual_alt_en="Cash ready for payment",
        visual_alt_es="Dinero en efectivo listo para pagar",
        visual_alt_he="כסף מזומן מוכן לתשלום",
        example_he="יֵשׁ לִי מְזֻמָּן.",
        example_en="I have cash.",
        example_es="Tengo efectivo.",
        example_romanization="Yesh li mezuman.",
        gender="masculine",
    ),
    _concept(
        word="כרטיס אשראי",
        niqqud="כַּרְטִיס אַשְׁרַאי",
        romanization="kartis ashray",
        pos="phrase",
        gloss_en="credit card",
        gloss_es="tarjeta de crédito",
        category="shopping",
        level="A1",
        visual_key="shopping.credit_card",
        visual_emoji="💳",
        visual_alt_en="A credit card beside a payment terminal",
        visual_alt_es="Una tarjeta de crédito junto a un terminal de pago",
        visual_alt_he="כרטיס אשראי ליד מסוף תשלום",
        example_he="אֶפְשָׁר לְשַׁלֵּם בְּכַרְטִיס אַשְׁרַאי.",
        example_en="You can pay by credit card.",
        example_es="Se puede pagar con tarjeta de crédito.",
        example_romanization="Efshar leshalem be-kartis ashray.",
        gender="masculine",
    ),
    _concept(
        word="מידה",
        niqqud="מִדָּה",
        romanization="mida",
        pos="noun",
        gloss_en="size",
        gloss_es="talla",
        category="shopping",
        level="A1",
        visual_key="shopping.size",
        visual_emoji="📏",
        visual_alt_en="A clothing size tag beside a ruler",
        visual_alt_es="Una etiqueta de talla junto a una regla",
        visual_alt_he="תווית מידה ליד סרגל",
        example_he="אֵיזוֹ מִדָּה זֹאת?",
        example_en="What size is this?",
        example_es="¿Qué talla es esta?",
        example_romanization="Eizo mida zot?",
        gender="feminine",
    ),
    _concept(
        word="כמה זה עולה",
        niqqud="כַּמָּה זֶה עוֹלֶה?",
        romanization="kama ze ole",
        pos="phrase",
        gloss_en="how much does this cost?",
        gloss_es="¿cuánto cuesta esto?",
        category="shopping",
        level="A0",
        visual_key="shopping.how_much",
        visual_emoji="🏷️",
        visual_alt_en="A shopper checking a price tag",
        visual_alt_es="Una persona mirando una etiqueta de precio",
        visual_alt_he="קונה בודק תג מחיר",
        example_he="כַּמָּה זֶה עוֹלֶה בִּשְׁקָלִים?",
        example_en="How much does this cost in shekels?",
        example_es="¿Cuánto cuesta esto en séqueles?",
        example_romanization="Kama ze ole bi-shkalim?",
    ),
    # Health: six additions bring the category to twelve concepts.
    _concept(
        word="בית מרקחת",
        niqqud="בֵּית מִרְקַחַת",
        romanization="beit mirkakhat",
        pos="phrase",
        gloss_en="pharmacy",
        gloss_es="farmacia",
        category="health",
        level="A1",
        visual_key="health.pharmacy",
        visual_emoji="⚕️",
        visual_alt_en="A neighborhood pharmacy with a medical sign",
        visual_alt_es="Una farmacia de barrio con un símbolo médico",
        visual_alt_he="בית מרקחת שכונתי עם סמל רפואי",
        example_he="בֵּית הַמִּרְקַחַת קָרוֹב לְכָאן.",
        example_en="The pharmacy is near here.",
        example_es="La farmacia está cerca de aquí.",
        example_romanization="Beit ha-mirkakhat karov le-khan.",
        gender="masculine",
    ),
    _concept(
        word="קופת חולים",
        niqqud="קֻפַּת חוֹלִים",
        romanization="kupat kholim",
        pos="phrase",
        gloss_en="health fund clinic",
        gloss_es="clínica de la caja de salud",
        category="health",
        level="A1",
        visual_key="health.health_fund",
        visual_emoji="🏥",
        visual_alt_en="An Israeli health fund clinic entrance",
        visual_alt_es="La entrada de una clínica de una caja de salud israelí",
        visual_alt_he="כניסה למרפאת קופת חולים בישראל",
        example_he="יֵשׁ לִי תּוֹר בְּקֻפַּת חוֹלִים.",
        example_en="I have an appointment at the health fund clinic.",
        example_es="Tengo una cita en la clínica de la caja de salud.",
        example_romanization="Yesh li tor be-kupat kholim.",
        gender="feminine",
    ),
    _concept(
        word="תור",
        niqqud="תּוֹר",
        romanization="tor",
        pos="noun",
        gloss_en="appointment",
        gloss_es="cita",
        category="health",
        level="A1",
        visual_key="health.appointment",
        visual_emoji="📅",
        visual_alt_en="A medical appointment marked on a calendar",
        visual_alt_es="Una cita médica marcada en un calendario",
        visual_alt_he="תור רפואי מסומן בלוח שנה",
        example_he="הַתּוֹר שֶׁלִּי בְּשָׁעָה שָׁלוֹשׁ.",
        example_en="My appointment is at three o'clock.",
        example_es="Mi cita es a las tres.",
        example_romanization="Ha-tor sheli be-sha'a shalosh.",
        gender="masculine",
    ),
    _concept(
        word="מרשם",
        niqqud="מִרְשָׁם",
        romanization="mirsham",
        pos="noun",
        gloss_en="prescription",
        gloss_es="receta médica",
        category="health",
        level="A1",
        visual_key="health.prescription",
        visual_emoji="📄",
        visual_alt_en="A doctor's prescription beside medicine",
        visual_alt_es="Una receta médica junto a un medicamento",
        visual_alt_he="מרשם רופא ליד תרופה",
        example_he="הָרוֹפֵא נָתַן לִי מִרְשָׁם.",
        example_en="The doctor gave me a prescription.",
        example_es="El médico me dio una receta.",
        example_romanization="Ha-rofe natan li mirsham.",
        gender="masculine",
    ),
    _concept(
        word="אלרגיה",
        niqqud="אָלֶרְגְּיָה",
        romanization="alergya",
        pos="noun",
        gloss_en="allergy",
        gloss_es="alergia",
        category="health",
        level="A1",
        visual_key="health.allergy",
        visual_emoji="⚠️",
        visual_alt_en="An allergy warning beside a glass of milk",
        visual_alt_es="Una advertencia de alergia junto a un vaso de leche",
        visual_alt_he="אזהרת אלרגיה ליד כוס חלב",
        example_he="יֵשׁ לִי אָלֶרְגְּיָה לְחָלָב.",
        example_en="I have a milk allergy.",
        example_es="Tengo alergia a la leche.",
        example_romanization="Yesh li alergya le-khalav.",
        gender="feminine",
    ),
    _concept(
        word="אמבולנס",
        niqqud="אַמְבּוּלַנְס",
        romanization="ambulans",
        pos="noun",
        gloss_en="ambulance",
        gloss_es="ambulancia",
        category="health",
        level="A1",
        visual_key="health.ambulance",
        visual_emoji="🚑",
        visual_alt_en="An ambulance ready for an emergency",
        visual_alt_es="Una ambulancia lista para una emergencia",
        visual_alt_he="אמבולנס מוכן למקרה חירום",
        example_he="תִּקְרְאוּ לְאַמְבּוּלַנְס.",
        example_en="Call an ambulance.",
        example_es="Llamen a una ambulancia.",
        example_romanization="Tikre'u le-ambulans.",
        gender="masculine",
    ),
    # Places: a new twelve-concept Israel-life category.
    _concept(
        word="ישראל",
        niqqud="יִשְׂרָאֵל",
        romanization="Yisrael",
        pos="proper noun",
        gloss_en="Israel",
        gloss_es="Israel",
        category="places",
        level="A0",
        visual_key="places.israel",
        visual_emoji="🇮🇱",
        visual_alt_en="A simple map silhouette of Israel",
        visual_alt_es="Una silueta sencilla del mapa de Israel",
        visual_alt_he="צללית פשוטה של מפת ישראל",
        example_he="אֲנַחְנוּ בְּיִשְׂרָאֵל.",
        example_en="We are in Israel.",
        example_es="Estamos en Israel.",
        example_romanization="Anakhnu be-Yisrael.",
    ),
    _concept(
        word="ירושלים",
        niqqud="יְרוּשָׁלַיִם",
        romanization="Yerushalayim",
        pos="proper noun",
        gloss_en="Jerusalem",
        gloss_es="Jerusalén",
        category="places",
        level="A0",
        visual_key="places.jerusalem",
        visual_emoji="🪨",
        visual_alt_en="Jerusalem stone buildings in warm light",
        visual_alt_es="Edificios de piedra de Jerusalén con luz cálida",
        visual_alt_he="בנייני אבן ירושלמית באור חם",
        example_he="יְרוּשָׁלַיִם עִיר יָפָה.",
        example_en="Jerusalem is a beautiful city.",
        example_es="Jerusalén es una ciudad hermosa.",
        example_romanization="Yerushalayim ir yafa.",
    ),
    _concept(
        word="תל אביב",
        niqqud="תֵּל אָבִיב",
        romanization="Tel Aviv",
        pos="proper noun",
        gloss_en="Tel Aviv",
        gloss_es="Tel Aviv",
        category="places",
        level="A0",
        visual_key="places.tel_aviv",
        visual_emoji="🏙️",
        visual_alt_en="Tel Aviv buildings beside the Mediterranean Sea",
        visual_alt_es="Edificios de Tel Aviv junto al mar Mediterráneo",
        visual_alt_he="בנייני תל אביב ליד הים התיכון",
        example_he="יֵשׁ רַכֶּבֶת לְתֵל אָבִיב.",
        example_en="There is a train to Tel Aviv.",
        example_es="Hay un tren a Tel Aviv.",
        example_romanization="Yesh rakevet le-Tel Aviv.",
    ),
    _concept(
        word="חיפה",
        niqqud="חֵיפָה",
        romanization="Kheifa",
        pos="proper noun",
        gloss_en="Haifa",
        gloss_es="Haifa",
        category="places",
        level="A0",
        visual_key="places.haifa",
        visual_emoji="⛰️",
        visual_alt_en="Haifa rising from the sea toward Mount Carmel",
        visual_alt_es="Haifa subiendo desde el mar hacia el monte Carmelo",
        visual_alt_he="חיפה עולה מן הים אל הר הכרמל",
        example_he="יֵשׁ רַכֶּבֶת לְחֵיפָה.",
        example_en="There is a train to Haifa.",
        example_es="Hay un tren a Haifa.",
        example_romanization="Yesh rakevet le-Kheifa.",
    ),
    _concept(
        word="באר שבע",
        niqqud="בְּאֵר שֶׁבַע",
        romanization="Be'er Sheva",
        pos="proper noun",
        gloss_en="Be'er Sheva",
        gloss_es="Beerseba",
        category="places",
        level="A0",
        visual_key="places.beer_sheva",
        visual_emoji="🏜️",
        visual_alt_en="Be'er Sheva beneath a wide Negev sky",
        visual_alt_es="Beerseba bajo un amplio cielo del Néguev",
        visual_alt_he="באר שבע מתחת לשמי הנגב הרחבים",
        example_he="בְּאֵר שֶׁבַע בַּנֶּגֶב.",
        example_en="Be'er Sheva is in the Negev.",
        example_es="Beerseba está en el Néguev.",
        example_romanization="Be'er Sheva ba-Negev.",
    ),
    _concept(
        word="עיר",
        niqqud="עִיר",
        romanization="ir",
        pos="noun",
        gloss_en="city",
        gloss_es="ciudad",
        category="places",
        level="A0",
        visual_key="places.city",
        visual_emoji="🏘️",
        visual_alt_en="A lively Israeli city neighborhood",
        visual_alt_es="Un barrio animado de una ciudad israelí",
        visual_alt_he="שכונה תוססת בעיר ישראלית",
        example_he="זֹאת עִיר גְּדוֹלָה.",
        example_en="This is a big city.",
        example_es="Esta es una ciudad grande.",
        example_romanization="Zot ir gdola.",
        gender="feminine",
    ),
    _concept(
        word="ים",
        niqqud="יָם",
        romanization="yam",
        pos="noun",
        gloss_en="sea",
        gloss_es="mar",
        category="places",
        level="A0",
        visual_key="places.sea",
        visual_emoji="🌊",
        visual_alt_en="Blue waves on the Mediterranean Sea",
        visual_alt_es="Olas azules del mar Mediterráneo",
        visual_alt_he="גלים כחולים בים התיכון",
        example_he="הַיָּם כָּחֹל הַיּוֹם.",
        example_en="The sea is blue today.",
        example_es="El mar está azul hoy.",
        example_romanization="Ha-yam kakhol ha-yom.",
        gender="masculine",
    ),
    _concept(
        word="חוף",
        niqqud="חוֹף",
        romanization="khof",
        pos="noun",
        gloss_en="beach",
        gloss_es="playa",
        category="places",
        level="A0",
        visual_key="places.beach",
        visual_emoji="🏖️",
        visual_alt_en="A sunny Mediterranean beach",
        visual_alt_es="Una playa mediterránea soleada",
        visual_alt_he="חוף ים תיכוני שטוף שמש",
        example_he="הַחוֹף יָפֶה.",
        example_en="The beach is beautiful.",
        example_es="La playa es hermosa.",
        example_romanization="Ha-khof yafe.",
        gender="masculine",
    ),
    _concept(
        word="פארק",
        niqqud="פַּארְק",
        romanization="park",
        pos="noun",
        gloss_en="park",
        gloss_es="parque",
        category="places",
        level="A0",
        visual_key="places.park",
        visual_emoji="🌳",
        visual_alt_en="Families relaxing in a green city park",
        visual_alt_es="Familias descansando en un parque urbano verde",
        visual_alt_he="משפחות נחות בפארק עירוני ירוק",
        example_he="הַיְלָדִים בַּפַּארְק.",
        example_en="The children are in the park.",
        example_es="Los niños están en el parque.",
        example_romanization="Ha-yeladim ba-park.",
        gender="masculine",
    ),
    _concept(
        word="מלון",
        niqqud="מָלוֹן",
        romanization="malon",
        pos="noun",
        gloss_en="hotel",
        gloss_es="hotel",
        category="places",
        level="A1",
        visual_key="places.hotel",
        visual_emoji="🏨",
        visual_alt_en="A welcoming hotel near the sea",
        visual_alt_es="Un hotel acogedor cerca del mar",
        visual_alt_he="מלון מזמין ליד הים",
        example_he="הַמָּלוֹן לְיַד הַיָּם.",
        example_en="The hotel is beside the sea.",
        example_es="El hotel está junto al mar.",
        example_romanization="Ha-malon le-yad ha-yam.",
        gender="masculine",
    ),
    _concept(
        word="בית ספר",
        niqqud="בֵּית סֵפֶר",
        romanization="beit sefer",
        pos="phrase",
        gloss_en="school",
        gloss_es="escuela",
        category="places",
        level="A0",
        visual_key="places.school",
        visual_emoji="🏫",
        visual_alt_en="A neighborhood school with an open gate",
        visual_alt_es="Una escuela de barrio con la entrada abierta",
        visual_alt_he="בית ספר שכונתי עם שער פתוח",
        example_he="בֵּית הַסֵּפֶר בָּרְחוֹב הַזֶּה.",
        example_en="The school is on this street.",
        example_es="La escuela está en esta calle.",
        example_romanization="Beit ha-sefer ba-rekhov ha-ze.",
        gender="masculine",
    ),
    _concept(
        word="בית כנסת",
        niqqud="בֵּית כְּנֶסֶת",
        romanization="beit kneset",
        pos="phrase",
        gloss_en="synagogue",
        gloss_es="sinagoga",
        category="places",
        level="A1",
        visual_key="places.synagogue",
        visual_emoji="🕍",
        visual_alt_en="A neighborhood synagogue entrance",
        visual_alt_es="La entrada de una sinagoga de barrio",
        visual_alt_he="כניסה לבית כנסת שכונתי",
        example_he="בֵּית הַכְּנֶסֶת פָּתוּחַ.",
        example_en="The synagogue is open.",
        example_es="La sinagoga está abierta.",
        example_romanization="Beit ha-kneset patuakh.",
        gender="masculine",
    ),
)
