"""Reviewed v2.8 additions to the built-in Hebrew starter lexicon.

Four everyday categories — numbers, time, weather, and nature — extend the
reviewed starter dictionary from 96 to 144 exact senses. Records follow the
same editorial contract as ``starter_lexicon_v2``: one reviewed niqqud form,
one practical trilingual example, and code-native visual metadata.
"""

from __future__ import annotations

from typing import Any

STARTER_PROVENANCE_V3 = "Ivrit Sheli editorial review; A0/A1 Israel-life sense v2.8"


def _concept(
    *,
    word: str,
    niqqud: str,
    romanization: str,
    pos: str,
    gloss_en: str,
    gloss_es: str,
    category: str,
    level: str,
    visual_key: str,
    visual_emoji: str,
    visual_alt_en: str,
    visual_alt_es: str,
    visual_alt_he: str,
    example_he: str,
    example_en: str,
    example_es: str,
    example_romanization: str,
    gender: str | None = None,
) -> dict[str, Any]:
    """Return one exact reviewed sense in the dictionary seed format."""
    return {
        "word": word,
        "pos": pos,
        "romanization": romanization,
        "gender": gender,
        # Root and binyan stay unknown unless a reviewed source establishes them.
        "root": None,
        "binyan": None,
        "source_key": None,
        "gloss_en": gloss_en,
        "gloss_es": gloss_es,
        "level": level,
        "category": category,
        "visual_key": visual_key,
        "visual_emoji": visual_emoji,
        "visual_alt_en": visual_alt_en,
        "visual_alt_es": visual_alt_es,
        "visual_alt_he": visual_alt_he,
        "provenance": STARTER_PROVENANCE_V3,
        "forms": [{"form": niqqud, "tags": ["with-niqqud"]}],
        "examples": [
            {
                "hebrew": example_he,
                "translation_en": example_en,
                "translation_es": example_es,
                "romanization": example_romanization,
            }
        ],
    }


LEARNING_EXPANSION_ENTRIES: tuple[dict[str, Any], ...] = (
    # Numbers: the feminine counting forms used in everyday Israeli speech.
    _concept(
        word="אחת",
        niqqud="אַחַת",
        romanization="akhat",
        pos="numeral",
        gloss_en="one",
        gloss_es="uno",
        category="numbers",
        level="A0",
        visual_key="numbers.one",
        visual_emoji="1️⃣",
        visual_alt_en="A single raised finger",
        visual_alt_es="Un solo dedo levantado",
        visual_alt_he="אצבע אחת מורמת",
        example_he="יֵשׁ לִי בַּת אַחַת.",
        example_en="I have one daughter.",
        example_es="Tengo una hija.",
        example_romanization="Yesh li bat akhat.",
        gender="feminine",
    ),
    _concept(
        word="שתיים",
        niqqud="שְׁתַּיִם",
        romanization="shtayim",
        pos="numeral",
        gloss_en="two",
        gloss_es="dos",
        category="numbers",
        level="A0",
        visual_key="numbers.two",
        visual_emoji="2️⃣",
        visual_alt_en="Two coffee cups on a table",
        visual_alt_es="Dos tazas de café sobre una mesa",
        visual_alt_he="שתי כוסות קפה על שולחן",
        example_he="שְׁתַּיִם, בְּבַקָּשָׁה.",
        example_en="Two, please.",
        example_es="Dos, por favor.",
        example_romanization="Shtayim, bevakasha.",
        gender="feminine",
    ),
    _concept(
        word="שלוש",
        niqqud="שָׁלוֹשׁ",
        romanization="shalosh",
        pos="numeral",
        gloss_en="three",
        gloss_es="tres",
        category="numbers",
        level="A0",
        visual_key="numbers.three",
        visual_emoji="3️⃣",
        visual_alt_en="A clock pointing to three",
        visual_alt_es="Un reloj marcando las tres",
        visual_alt_he="שעון שמראה שלוש",
        example_he="הַשִּׁעוּר בְּשָׁעָה שָׁלוֹשׁ.",
        example_en="The lesson is at three o'clock.",
        example_es="La clase es a las tres.",
        example_romanization="Ha-shi'ur be-sha'a shalosh.",
        gender="feminine",
    ),
    _concept(
        word="ארבע",
        niqqud="אַרְבַּע",
        romanization="arba",
        pos="numeral",
        gloss_en="four",
        gloss_es="cuatro",
        category="numbers",
        level="A0",
        visual_key="numbers.four",
        visual_emoji="4️⃣",
        visual_alt_en="An elevator button for the fourth floor",
        visual_alt_es="Un botón de ascensor del cuarto piso",
        visual_alt_he="כפתור מעלית לקומה הרביעית",
        example_he="אֲנִי גָּרָה בְּקוֹמָה אַרְבַּע.",
        example_en="I live on the fourth floor.",
        example_es="Vivo en el cuarto piso.",
        example_romanization="Ani gara be-koma arba.",
        gender="feminine",
    ),
    _concept(
        word="חמש",
        niqqud="חָמֵשׁ",
        romanization="khamesh",
        pos="numeral",
        gloss_en="five",
        gloss_es="cinco",
        category="numbers",
        level="A0",
        visual_key="numbers.five",
        visual_emoji="5️⃣",
        visual_alt_en="An open hand showing five fingers",
        visual_alt_es="Una mano abierta mostrando cinco dedos",
        visual_alt_he="כף יד פתוחה עם חמש אצבעות",
        example_he="הַחֲנוּת נִסְגֶּרֶת בְּחָמֵשׁ.",
        example_en="The shop closes at five.",
        example_es="La tienda cierra a las cinco.",
        example_romanization="Ha-khanut nisgeret be-khamesh.",
        gender="feminine",
    ),
    _concept(
        word="שש",
        niqqud="שֵׁשׁ",
        romanization="shesh",
        pos="numeral",
        gloss_en="six",
        gloss_es="seis",
        category="numbers",
        level="A0",
        visual_key="numbers.six",
        visual_emoji="6️⃣",
        visual_alt_en="A bus arriving at a stop",
        visual_alt_es="Un autobús llegando a la parada",
        visual_alt_he="אוטובוס מגיע לתחנה",
        example_he="הָאוֹטוֹבּוּס מַגִּיעַ בְּשֵׁשׁ.",
        example_en="The bus arrives at six.",
        example_es="El autobús llega a las seis.",
        example_romanization="Ha-otobus magia be-shesh.",
        gender="feminine",
    ),
    _concept(
        word="שבע",
        niqqud="שֶׁבַע",
        romanization="sheva",
        pos="numeral",
        gloss_en="seven",
        gloss_es="siete",
        category="numbers",
        level="A0",
        visual_key="numbers.seven",
        visual_emoji="7️⃣",
        visual_alt_en="An alarm clock ringing in the morning",
        visual_alt_es="Un despertador sonando por la mañana",
        visual_alt_he="שעון מעורר מצלצל בבוקר",
        example_he="אֲנִי קָמָה בְּשֶׁבַע.",
        example_en="I get up at seven.",
        example_es="Me levanto a las siete.",
        example_romanization="Ani kama be-sheva.",
        gender="feminine",
    ),
    _concept(
        word="שמונה",
        niqqud="שְׁמוֹנֶה",
        romanization="shmone",
        pos="numeral",
        gloss_en="eight",
        gloss_es="ocho",
        category="numbers",
        level="A0",
        visual_key="numbers.eight",
        visual_emoji="8️⃣",
        visual_alt_en="An office door opening at work",
        visual_alt_es="La puerta de una oficina abriéndose",
        visual_alt_he="דלת משרד נפתחת בעבודה",
        example_he="הָעֲבוֹדָה מַתְחִילָה בִּשְׁמוֹנֶה.",
        example_en="Work starts at eight.",
        example_es="El trabajo empieza a las ocho.",
        example_romanization="Ha-avoda matkhila bi-shmone.",
        gender="feminine",
    ),
    _concept(
        word="תשע",
        niqqud="תֵּשַׁע",
        romanization="tesha",
        pos="numeral",
        gloss_en="nine",
        gloss_es="nueve",
        category="numbers",
        level="A0",
        visual_key="numbers.nine",
        visual_emoji="9️⃣",
        visual_alt_en="A waiting room with an appointment ticket",
        visual_alt_es="Una sala de espera con un turno",
        visual_alt_he="חדר המתנה עם פתק תור",
        example_he="הַתּוֹר שֶׁלִּי בְּתֵשַׁע.",
        example_en="My appointment is at nine.",
        example_es="Mi cita es a las nueve.",
        example_romanization="Ha-tor sheli be-tesha.",
        gender="feminine",
    ),
    _concept(
        word="עשר",
        niqqud="עֶשֶׂר",
        romanization="eser",
        pos="numeral",
        gloss_en="ten",
        gloss_es="diez",
        category="numbers",
        level="A0",
        visual_key="numbers.ten",
        visual_emoji="🔟",
        visual_alt_en="Footsteps on a short walking path",
        visual_alt_es="Pasos en un camino corto",
        visual_alt_he="צעדים על שביל הליכה קצר",
        example_he="עֶשֶׂר דַּקּוֹת בָּרֶגֶל.",
        example_en="Ten minutes on foot.",
        example_es="Diez minutos a pie.",
        example_romanization="Eser dakot ba-regel.",
        gender="feminine",
    ),
    _concept(
        word="מאה",
        niqqud="מֵאָה",
        romanization="mea",
        pos="numeral",
        gloss_en="one hundred",
        gloss_es="cien",
        category="numbers",
        level="A1",
        visual_key="numbers.hundred",
        visual_emoji="💯",
        visual_alt_en="A price tag at the market",
        visual_alt_es="Una etiqueta de precio en el mercado",
        visual_alt_he="תווית מחיר בשוק",
        example_he="זֶה עוֹלֶה מֵאָה שְׁקָלִים.",
        example_en="It costs one hundred shekels.",
        example_es="Cuesta cien shékels.",
        example_romanization="Ze ole mea shkalim.",
    ),
    _concept(
        word="מספר",
        niqqud="מִסְפָּר",
        romanization="mispar",
        pos="noun",
        gloss_en="number",
        gloss_es="número",
        category="numbers",
        level="A1",
        visual_key="numbers.number",
        visual_emoji="🔢",
        visual_alt_en="A phone keypad with digits",
        visual_alt_es="Un teclado de teléfono con dígitos",
        visual_alt_he="לוח מקשים של טלפון עם ספרות",
        example_he="מַה מִּסְפַּר הַטֶּלֶפוֹן שֶׁלְּךָ?",
        example_en="What is your phone number?",
        example_es="¿Cuál es tu número de teléfono?",
        example_romanization="Ma mispar ha-telefon shelkha?",
        gender="masculine",
    ),
    # Time: the words that anchor appointments, plans, and daily rhythm.
    _concept(
        word="שעה",
        niqqud="שָׁעָה",
        romanization="sha'a",
        pos="noun",
        gloss_en="hour",
        gloss_es="hora",
        category="time",
        level="A0",
        visual_key="time.hour",
        visual_emoji="🕐",
        visual_alt_en="A round wall clock",
        visual_alt_es="Un reloj redondo de pared",
        visual_alt_he="שעון קיר עגול",
        example_he="בְּעוֹד שָׁעָה אֲנִי בַּבַּיִת.",
        example_en="In an hour I will be home.",
        example_es="En una hora estoy en casa.",
        example_romanization="Be-od sha'a ani ba-bayit.",
        gender="feminine",
    ),
    _concept(
        word="דקה",
        niqqud="דַּקָּה",
        romanization="daka",
        pos="noun",
        gloss_en="minute",
        gloss_es="minuto",
        category="time",
        level="A0",
        visual_key="time.minute",
        visual_emoji="⏱️",
        visual_alt_en="A stopwatch counting seconds",
        visual_alt_es="Un cronómetro contando segundos",
        visual_alt_he="שעון עצר סופר שניות",
        example_he="עוֹד דַּקָּה, בְּבַקָּשָׁה.",
        example_en="One more minute, please.",
        example_es="Un minuto más, por favor.",
        example_romanization="Od daka, bevakasha.",
        gender="feminine",
    ),
    _concept(
        word="יום",
        niqqud="יוֹם",
        romanization="yom",
        pos="noun",
        gloss_en="day",
        gloss_es="día",
        category="time",
        level="A0",
        visual_key="time.day",
        visual_emoji="📅",
        visual_alt_en="A single calendar page",
        visual_alt_es="Una hoja de calendario",
        visual_alt_he="דף לוח שנה בודד",
        example_he="אֵיזֶה יוֹם הַיּוֹם?",
        example_en="What day is it today?",
        example_es="¿Qué día es hoy?",
        example_romanization="Eize yom ha-yom?",
        gender="masculine",
    ),
    _concept(
        word="שבוע",
        niqqud="שָׁבוּעַ",
        romanization="shavua",
        pos="noun",
        gloss_en="week",
        gloss_es="semana",
        category="time",
        level="A0",
        visual_key="time.week",
        visual_emoji="🗓️",
        visual_alt_en="A weekly planner with seven columns",
        visual_alt_es="Una agenda semanal con siete columnas",
        visual_alt_he="לוח שבועי עם שבע עמודות",
        example_he="נִתְרָאֶה בְּעוֹד שָׁבוּעַ.",
        example_en="See you in a week.",
        example_es="Nos vemos en una semana.",
        example_romanization="Nitra'e be-od shavua.",
        gender="masculine",
    ),
    _concept(
        word="חודש",
        niqqud="חֹדֶשׁ",
        romanization="khodesh",
        pos="noun",
        gloss_en="month",
        gloss_es="mes",
        category="time",
        level="A0",
        visual_key="time.month",
        visual_emoji="📆",
        visual_alt_en="A full month calendar",
        visual_alt_es="Un calendario de mes completo",
        visual_alt_he="לוח שנה של חודש שלם",
        example_he="בְּעוֹד חֹדֶשׁ יֵשׁ חַג.",
        example_en="In a month there is a holiday.",
        example_es="En un mes hay un día festivo.",
        example_romanization="Be-od khodesh yesh khag.",
        gender="masculine",
    ),
    _concept(
        word="שנה",
        niqqud="שָׁנָה",
        romanization="shana",
        pos="noun",
        gloss_en="year",
        gloss_es="año",
        category="time",
        level="A0",
        visual_key="time.year",
        visual_emoji="🎆",
        visual_alt_en="A circular year wheel divided into four changing seasons",
        visual_alt_es="Una rueda anual circular dividida en cuatro estaciones",
        visual_alt_he="גלגל שנה עגול המחולק לארבע עונות מתחלפות",
        example_he="שָׁנָה טוֹבָה!",
        example_en="Happy new year! (literally: a good year)",
        example_es="¡Feliz año nuevo! (literalmente: buen año)",
        example_romanization="Shana tova!",
        gender="feminine",
    ),
    _concept(
        word="היום",
        niqqud="הַיּוֹם",
        romanization="ha-yom",
        pos="adverb",
        gloss_en="today",
        gloss_es="hoy",
        category="time",
        level="A0",
        visual_key="time.today",
        visual_emoji="🌞",
        visual_alt_en="A hand points to the highlighted current day on a calendar",
        visual_alt_es="Una mano señala el día actual resaltado en un calendario",
        visual_alt_he="יד מצביעה על היום הנוכחי שמודגש בלוח שנה",
        example_he="הַיּוֹם אֲנִי לוֹמֶדֶת עִבְרִית.",
        example_en="Today I am learning Hebrew.",
        example_es="Hoy estoy aprendiendo hebreo.",
        example_romanization="Hayom ani lomedet ivrit.",
    ),
    _concept(
        word="מחר",
        niqqud="מָחָר",
        romanization="makhar",
        pos="adverb",
        gloss_en="tomorrow",
        gloss_es="mañana (día siguiente)",
        category="time",
        level="A0",
        visual_key="time.tomorrow",
        visual_emoji="🌅",
        visual_alt_en="An arrow moves from the current calendar page to the next day",
        visual_alt_es="Una flecha avanza de la página actual del calendario al día siguiente",
        visual_alt_he="חץ עובר מדף לוח השנה הנוכחי אל היום הבא",
        example_he="מָחָר נִפָּגֵשׁ בַּבֹּקֶר.",
        example_en="Tomorrow we meet in the morning.",
        example_es="Mañana nos encontramos por la mañana.",
        example_romanization="Makhar nipagesh ba-boker.",
    ),
    _concept(
        word="אתמול",
        niqqud="אֶתְמוֹל",
        romanization="etmol",
        pos="adverb",
        gloss_en="yesterday",
        gloss_es="ayer",
        category="time",
        level="A0",
        visual_key="time.yesterday",
        visual_emoji="🌙",
        visual_alt_en="Two calendar pages with an arrow pointing back to the previous day",
        visual_alt_es="Dos páginas de calendario con una flecha hacia el día anterior",
        visual_alt_he="שני דפי לוח שנה עם חץ החוזר אל היום הקודם",
        example_he="אֶתְמוֹל הָיִיתִי בַּשּׁוּק.",
        example_en="Yesterday I was at the market.",
        example_es="Ayer estuve en el mercado.",
        example_romanization="Etmol hayiti ba-shuk.",
    ),
    _concept(
        word="בוקר",
        niqqud="בֹּקֶר",
        romanization="boker",
        pos="noun",
        gloss_en="morning",
        gloss_es="mañana (parte del día)",
        category="time",
        level="A0",
        visual_key="time.morning",
        visual_emoji="☕",
        visual_alt_en="A cup of coffee in morning light",
        visual_alt_es="Una taza de café con luz de la mañana",
        visual_alt_he="כוס קפה באור הבוקר",
        example_he="אֲנִי אוֹהֶבֶת קָפֶה בַּבֹּקֶר.",
        example_en="I love coffee in the morning.",
        example_es="Me encanta el café por la mañana.",
        example_romanization="Ani ohevet kafe ba-boker.",
        gender="masculine",
    ),
    _concept(
        word="ערב",
        niqqud="עֶרֶב",
        romanization="erev",
        pos="noun",
        gloss_en="evening",
        gloss_es="tarde (al anochecer)",
        category="time",
        level="A0",
        visual_key="time.evening",
        visual_emoji="🌆",
        visual_alt_en="Warm windows lit in the evening",
        visual_alt_es="Ventanas iluminadas al anochecer",
        visual_alt_he="חלונות מוארים בשעת ערב",
        example_he="בָּעֶרֶב אֲנַחְנוּ בַּבַּיִת.",
        example_en="In the evening we are at home.",
        example_es="Al anochecer estamos en casa.",
        example_romanization="Ba-erev anakhnu ba-bayit.",
        gender="masculine",
    ),
    _concept(
        word="עכשיו",
        niqqud="עַכְשָׁו",
        romanization="akhshav",
        pos="adverb",
        gloss_en="now",
        gloss_es="ahora",
        category="time",
        level="A0",
        visual_key="time.now",
        visual_emoji="⏳",
        visual_alt_en="A clock and motion lines show a person starting immediately",
        visual_alt_es="Un reloj y líneas de movimiento muestran a una persona empezando de inmediato",
        visual_alt_he="שעון וקווי תנועה מראים אדם שמתחיל מיד",
        example_he="אֲנִי פְּנוּיָה עַכְשָׁו.",
        example_en="I am free now.",
        example_es="Estoy libre ahora.",
        example_romanization="Ani pnuya akhshav.",
    ),
    # Weather: what Israelis actually talk about between seasons.
    _concept(
        word="שמש",
        niqqud="שֶׁמֶשׁ",
        romanization="shemesh",
        pos="noun",
        gloss_en="sun",
        gloss_es="sol",
        category="weather",
        level="A0",
        visual_key="weather.sun",
        visual_emoji="🌞",
        visual_alt_en="A bright sun in a clear sky",
        visual_alt_es="Un sol brillante en un cielo despejado",
        visual_alt_he="שמש בהירה בשמיים נקיים",
        example_he="יֵשׁ הַרְבֵּה שֶׁמֶשׁ הַיּוֹם.",
        example_en="There is a lot of sun today.",
        example_es="Hay mucho sol hoy.",
        example_romanization="Yesh harbe shemesh ha-yom.",
        gender="feminine",
    ),
    _concept(
        word="גשם",
        niqqud="גֶּשֶׁם",
        romanization="geshem",
        pos="noun",
        gloss_en="rain",
        gloss_es="lluvia",
        category="weather",
        level="A0",
        visual_key="weather.rain",
        visual_emoji="🌧️",
        visual_alt_en="Rain falling on a window",
        visual_alt_es="Lluvia cayendo sobre una ventana",
        visual_alt_he="גשם יורד על חלון",
        example_he="יוֹרֵד גֶּשֶׁם בַּחוּץ.",
        example_en="It is raining outside.",
        example_es="Está lloviendo afuera.",
        example_romanization="Yored geshem ba-khuts.",
        gender="masculine",
    ),
    _concept(
        word="רוח",
        niqqud="רוּחַ",
        romanization="ruakh",
        pos="noun",
        gloss_en="wind",
        gloss_es="viento",
        category="weather",
        level="A1",
        visual_key="weather.wind",
        visual_emoji="💨",
        visual_alt_en="Wind bending trees on a hill",
        visual_alt_es="Viento inclinando árboles en una colina",
        visual_alt_he="רוח מכופפת עצים על גבעה",
        example_he="יֵשׁ רוּחַ חֲזָקָה הַיּוֹם.",
        example_en="There is a strong wind today.",
        example_es="Hay un viento fuerte hoy.",
        example_romanization="Yesh ruakh khazaka ha-yom.",
        gender="feminine",
    ),
    _concept(
        word="חם",
        niqqud="חַם",
        romanization="kham",
        pos="adjective",
        gloss_en="hot",
        gloss_es="caliente; (clima) caluroso",
        category="weather",
        level="A0",
        visual_key="weather.hot",
        visual_emoji="🥵",
        visual_alt_en="A person sweats under the sun and cools down beside a glass of water at a bus stop",
        visual_alt_es="Una persona suda bajo el sol y se refresca junto a un vaso de agua en una parada de autobús",
        visual_alt_he="אדם מזיע תחת השמש ומצטנן ליד כוס מים בתחנת אוטובוס",
        example_he="חַם מְאוֹד בַּקַּיִץ.",
        example_en="It is very hot in the summer.",
        example_es="Hace mucho calor en verano.",
        example_romanization="Kham me'od ba-kayits.",
    ),
    _concept(
        word="קר",
        niqqud="קַר",
        romanization="kar",
        pos="adjective",
        gloss_en="cold",
        gloss_es="frío",
        category="weather",
        level="A0",
        visual_key="weather.cold",
        visual_emoji="🥶",
        visual_alt_en="A person shivers in a scarf under a cold cloud at a bus stop",
        visual_alt_es="Una persona tiembla con bufanda bajo una nube fría en una parada de autobús",
        visual_alt_he="אדם רועד עם צעיף תחת ענן קר בתחנת אוטובוס",
        example_he="קַר לִי, אֲנִי צְרִיכָה מְעִיל.",
        example_en="I am cold, I need a coat.",
        example_es="Tengo frío, necesito un abrigo.",
        example_romanization="Kar li, ani tsrikha me'il.",
    ),
    _concept(
        word="ענן",
        niqqud="עָנָן",
        romanization="anan",
        pos="noun",
        gloss_en="cloud",
        gloss_es="nube",
        category="weather",
        level="A1",
        visual_key="weather.cloud",
        visual_emoji="☁️",
        visual_alt_en="Gray clouds gathering",
        visual_alt_es="Nubes grises acumulándose",
        visual_alt_he="עננים אפורים מתקבצים",
        example_he="יֵשׁ עֲנָנִים אֲפֹרִים בַּשָּׁמַיִם.",
        example_en="There are gray clouds in the sky.",
        example_es="Hay nubes grises en el cielo.",
        example_romanization="Yesh ananim aforim ba-shamayim.",
        gender="masculine",
    ),
    _concept(
        word="שמיים",
        niqqud="שָׁמַיִם",
        romanization="shamayim",
        pos="noun",
        gloss_en="sky",
        gloss_es="cielo",
        category="weather",
        level="A1",
        visual_key="weather.sky",
        visual_emoji="🌌",
        visual_alt_en="A wide open blue sky",
        visual_alt_es="Un cielo azul amplio y abierto",
        visual_alt_he="שמיים כחולים ופתוחים",
        example_he="הַשָּׁמַיִם כְּחֻלִּים הַיּוֹם.",
        example_en="The sky is blue today.",
        example_es="El cielo está azul hoy.",
        example_romanization="Ha-shamayim kkhulim ha-yom.",
        gender="masculine",
    ),
    _concept(
        word="חורף",
        niqqud="חֹרֶף",
        romanization="khoref",
        pos="noun",
        gloss_en="winter",
        gloss_es="invierno",
        category="weather",
        level="A0",
        visual_key="weather.winter",
        visual_emoji="❄️",
        visual_alt_en="An umbrella and boots by a door",
        visual_alt_es="Un paraguas y botas junto a la puerta",
        visual_alt_he="מטרייה ומגפיים ליד דלת",
        example_he="בַּחֹרֶף יוֹרֵד גֶּשֶׁם.",
        example_en="In winter it rains.",
        example_es="En invierno llueve.",
        example_romanization="Ba-khoref yored geshem.",
        gender="masculine",
    ),
    _concept(
        word="קיץ",
        niqqud="קַיִץ",
        romanization="kayits",
        pos="noun",
        gloss_en="summer",
        gloss_es="verano",
        category="weather",
        level="A0",
        visual_key="weather.summer",
        visual_emoji="🍉",
        visual_alt_en="Watermelon slices on a summer day",
        visual_alt_es="Rebanadas de sandía en un día de verano",
        visual_alt_he="פלחי אבטיח ביום קיץ",
        example_he="בַּקַּיִץ הוֹלְכִים לַיָּם.",
        example_en="In summer people go to the sea.",
        example_es="En verano se va al mar.",
        example_romanization="Ba-kayits holkhim la-yam.",
        gender="masculine",
    ),
    _concept(
        word="מזג אוויר",
        niqqud="מֶזֶג אֲוִיר",
        romanization="mezeg avir",
        pos="noun",
        gloss_en="weather",
        gloss_es="clima",
        category="weather",
        level="A1",
        visual_key="weather.weather",
        visual_emoji="🌦️",
        visual_alt_en="A weather forecast with sun and rain",
        visual_alt_es="Un pronóstico con sol y lluvia",
        visual_alt_he="תחזית מזג אוויר עם שמש וגשם",
        example_he="אֵיךְ מֶזֶג הָאֲוִיר הַיּוֹם?",
        example_en="How is the weather today?",
        example_es="¿Cómo está el clima hoy?",
        example_romanization="Eikh mezeg ha-avir ha-yom?",
        gender="masculine",
    ),
    _concept(
        word="חמסין",
        niqqud="חַמְסִין",
        romanization="khamsin",
        pos="noun",
        gloss_en="heat wave (hot desert wind)",
        gloss_es="ola de calor (viento del desierto)",
        category="weather",
        level="A1",
        visual_key="weather.heat_wave",
        visual_emoji="🌡️",
        visual_alt_en="A hazy hot day over dry hills",
        visual_alt_es="Un día caluroso y brumoso sobre colinas secas",
        visual_alt_he="יום חם ואביך מעל גבעות יבשות",
        example_he="יֵשׁ חַמְסִין, שְׁתוּ הַרְבֵּה מַיִם.",
        example_en="There is a heat wave, drink a lot of water.",
        example_es="Hay una ola de calor, beban mucha agua.",
        example_romanization="Yesh khamsin, shtu harbe mayim.",
        gender="masculine",
    ),
    _concept(
        word="מטרייה",
        niqqud="מִטְרִיָּה",
        romanization="mitriya",
        pos="noun",
        gloss_en="umbrella",
        gloss_es="paraguas",
        category="weather",
        level="A1",
        visual_key="weather.umbrella",
        visual_emoji="☂️",
        visual_alt_en="An open umbrella under rain",
        visual_alt_es="Un paraguas abierto bajo la lluvia",
        visual_alt_he="מטרייה פתוחה בגשם",
        example_he="אַל תִּשְׁכְּחִי מִטְרִיָּה!",
        example_en="Don't forget an umbrella!",
        example_es="¡No olvides un paraguas!",
        example_romanization="Al tishkekhi mitriya!",
        gender="feminine",
    ),
    # Nature: the landscapes and small creatures of everyday Israel.
    _concept(
        word="מדבר",
        niqqud="מִדְבָּר",
        romanization="midbar",
        pos="noun",
        gloss_en="desert",
        gloss_es="desierto",
        category="nature",
        level="A1",
        visual_key="nature.desert",
        visual_emoji="🏜️",
        visual_alt_en="Golden dunes in the Negev desert",
        visual_alt_es="Dunas doradas en el desierto del Néguev",
        visual_alt_he="דיונות זהובות במדבר הנגב",
        example_he="הַנֶּגֶב הוּא מִדְבָּר גָּדוֹל.",
        example_en="The Negev is a big desert.",
        example_es="El Néguev es un desierto grande.",
        example_romanization="Ha-Negev hu midbar gadol.",
        gender="masculine",
    ),
    _concept(
        word="הר",
        niqqud="הַר",
        romanization="har",
        pos="noun",
        gloss_en="mountain",
        gloss_es="montaña",
        category="nature",
        level="A0",
        visual_key="nature.mountain",
        visual_emoji="⛰️",
        visual_alt_en="A hiking trail up a mountain",
        visual_alt_es="Un sendero subiendo una montaña",
        visual_alt_he="שביל טיול במעלה הר",
        example_he="אֲנַחְנוּ מְטַיְּלִים בָּהָר.",
        example_en="We hike on the mountain.",
        example_es="Caminamos por la montaña.",
        example_romanization="Anakhnu metaylim ba-har.",
        gender="masculine",
    ),
    _concept(
        word="עץ",
        niqqud="עֵץ",
        romanization="ets",
        pos="noun",
        gloss_en="tree",
        gloss_es="árbol",
        category="nature",
        level="A0",
        visual_key="nature.tree",
        visual_emoji="🌳",
        visual_alt_en="An olive tree in a garden",
        visual_alt_es="Un olivo en un jardín",
        visual_alt_he="עץ זית בגינה",
        example_he="יֵשׁ עֵץ זַיִת בַּגִּנָּה.",
        example_en="There is an olive tree in the garden.",
        example_es="Hay un olivo en el jardín.",
        example_romanization="Yesh ets zayit ba-gina.",
        gender="masculine",
    ),
    _concept(
        word="פרח",
        niqqud="פֶּרַח",
        romanization="perakh",
        pos="noun",
        gloss_en="flower",
        gloss_es="flor",
        category="nature",
        level="A0",
        visual_key="nature.flower",
        visual_emoji="🌸",
        visual_alt_en="A fresh bouquet for Shabbat",
        visual_alt_es="Un ramo fresco para Shabat",
        visual_alt_he="זר פרחים טרי לשבת",
        example_he="קָנִיתִי פְּרָחִים לְשַׁבָּת.",
        example_en="I bought flowers for Shabbat.",
        example_es="Compré flores para Shabat.",
        example_romanization="Kaniti prakhim le-Shabat.",
        gender="masculine",
    ),
    _concept(
        word="טבע",
        niqqud="טֶבַע",
        romanization="teva",
        pos="noun",
        gloss_en="nature",
        gloss_es="naturaleza",
        category="nature",
        level="A1",
        visual_key="nature.nature",
        visual_emoji="🌿",
        visual_alt_en="Green hills in northern Israel",
        visual_alt_es="Colinas verdes en el norte de Israel",
        visual_alt_he="גבעות ירוקות בצפון הארץ",
        example_he="אֲנִי אוֹהֶבֶת אֶת הַטֶּבַע בַּצָּפוֹן.",
        example_en="I love nature in the north.",
        example_es="Me encanta la naturaleza del norte.",
        example_romanization="Ani ohevet et ha-teva ba-tsafon.",
        gender="masculine",
    ),
    _concept(
        word="גינה",
        niqqud="גִּנָּה",
        romanization="gina",
        pos="noun",
        gloss_en="garden; neighborhood park",
        gloss_es="jardín; parque de barrio",
        category="nature",
        level="A0",
        visual_key="nature.garden",
        visual_emoji="🛝",
        visual_alt_en="Children playing in a neighborhood playground",
        visual_alt_es="Niños jugando en un parque del barrio",
        visual_alt_he="ילדים משחקים בגינה שכונתית",
        example_he="הַיְלָדִים מְשַׂחֲקִים בַּגִּנָּה.",
        example_en="The children are playing in the park.",
        example_es="Los niños juegan en el parque.",
        example_romanization="Ha-yeladim mesakhakim ba-gina.",
        gender="feminine",
    ),
    _concept(
        word="ציפור",
        niqqud="צִפּוֹר",
        romanization="tsipor",
        pos="noun",
        gloss_en="bird",
        gloss_es="pájaro",
        category="nature",
        level="A0",
        visual_key="nature.bird",
        visual_emoji="🐦",
        visual_alt_en="A small bird on a branch",
        visual_alt_es="Un pájaro pequeño en una rama",
        visual_alt_he="ציפור קטנה על ענף",
        example_he="יֵשׁ צִפּוֹר עַל הָעֵץ.",
        example_en="There is a bird on the tree.",
        example_es="Hay un pájaro en el árbol.",
        example_romanization="Yesh tsipor al ha-ets.",
        gender="feminine",
    ),
    _concept(
        word="כלב",
        niqqud="כֶּלֶב",
        romanization="kelev",
        pos="noun",
        gloss_en="dog",
        gloss_es="perro",
        category="nature",
        level="A0",
        visual_key="nature.dog",
        visual_emoji="🐕",
        visual_alt_en="A small friendly dog",
        visual_alt_es="Un perro pequeño y amistoso",
        visual_alt_he="כלב קטן וידידותי",
        example_he="יֵשׁ לָנוּ כֶּלֶב קָטָן.",
        example_en="We have a small dog.",
        example_es="Tenemos un perro pequeño.",
        example_romanization="Yesh lanu kelev katan.",
        gender="masculine",
    ),
    _concept(
        word="חתול",
        niqqud="חָתוּל",
        romanization="khatul",
        pos="noun",
        gloss_en="cat",
        gloss_es="gato",
        category="nature",
        level="A0",
        visual_key="nature.cat",
        visual_emoji="🐈",
        visual_alt_en="A street cat resting in the shade",
        visual_alt_es="Un gato callejero descansando a la sombra",
        visual_alt_he="חתול רחוב נח בצל",
        example_he="בְּיִשְׂרָאֵל יֵשׁ הַרְבֵּה חֲתוּלִים.",
        example_en="In Israel there are many cats.",
        example_es="En Israel hay muchos gatos.",
        example_romanization="Be-Yisrael yesh harbe khatulim.",
        gender="masculine",
    ),
    _concept(
        word="נחל",
        niqqud="נַחַל",
        romanization="nakhal",
        pos="noun",
        gloss_en="stream",
        gloss_es="arroyo",
        category="nature",
        level="A1",
        visual_key="nature.stream",
        visual_emoji="🏞️",
        visual_alt_en="A clear stream in the Galilee",
        visual_alt_es="Un arroyo claro en la Galilea",
        visual_alt_he="נחל צלול בגליל",
        example_he="טִיַּלְנוּ לְיַד הַנַּחַל בַּגָּלִיל.",
        example_en="We walked by the stream in the Galilee.",
        example_es="Paseamos junto al arroyo en la Galilea.",
        example_romanization="Tiyalnu leyad ha-nakhal ba-Galil.",
        gender="masculine",
    ),
    _concept(
        word="שדה",
        niqqud="שָׂדֶה",
        romanization="sade",
        pos="noun",
        gloss_en="field",
        gloss_es="campo",
        category="nature",
        level="A1",
        visual_key="nature.field",
        visual_emoji="🌾",
        visual_alt_en="A green field beside a village",
        visual_alt_es="Un campo verde junto a un pueblo",
        visual_alt_he="שדה ירוק ליד כפר",
        example_he="יֵשׁ שָׂדֶה יָרֹק לְיַד הַכְּפָר.",
        example_en="There is a green field next to the village.",
        example_es="Hay un campo verde junto al pueblo.",
        example_romanization="Yesh sade yarok leyad ha-kfar.",
        gender="masculine",
    ),
    _concept(
        word="יער",
        niqqud="יַעַר",
        romanization="ya'ar",
        pos="noun",
        gloss_en="forest",
        gloss_es="bosque",
        category="nature",
        level="A1",
        visual_key="nature.forest",
        visual_emoji="🌲",
        visual_alt_en="A shaded forest path on the Carmel",
        visual_alt_es="Un sendero sombreado en el bosque del Carmelo",
        visual_alt_he="שביל מוצל ביער בכרמל",
        example_he="בַּכַּרְמֶל יֵשׁ יַעַר גָּדוֹל.",
        example_en="On the Carmel there is a big forest.",
        example_es="En el Carmelo hay un bosque grande.",
        example_romanization="Ba-Karmel yesh ya'ar gadol.",
        gender="masculine",
    ),
)
